from django.urls import path
from . import views

urlpatterns = [
    path('amp_bible/', views.amp_bible, name='amp_bible'),
    path('amp_chapters/', views.amp_chapters, name='amp_chapters'), 
    path('amp_verse/', views.amp_verse, name='amp_verse'),
    path('amp_verse_range/', views.amp_verse_range, name='amp_verse_range'),
    path('amp_keyword/', views.amp_keyword, name='amp_keyword'),
    path('esv_bible/', views.esv_bible, name='esv_bible'),
    path('esv_chapters/', views.esv_chapters, name='esv_chapters'), 
    path('esv_verse/', views.esv_verse, name='esv_verse'),
    path('esv_verse_range/', views.esv_verse_range, name='esv_verse_range'),
    path('esv_keyword/', views.esv_keyword, name='esv_keyword'),
    path('kjv_bible/', views.kjv_bible, name='kjv_bible'),
    path('kjv_chapters/', views.kjv_chapters, name='kjv_chapters'), 
    path('kjv_verse/', views.kjv_verse, name='kjv_verse'),
    path('kjv_verse_range/', views.kjv_verse_range, name='kjv_verse_range'),
    path('kjv_keyword/', views.kjv_keyword, name='kjv_keyword'),
    path('nkjv_bible/', views.nkjv_bible, name='nkjv_bible'),
    path('nkjv_chapters/', views.nkjv_chapters, name='nkjv_chapters'), 
    path('nkjv_verse/', views.nkjv_verse, name='nkjv_verse'),
    path('nkjv_verse_range/', views.nkjv_verse_range, name='nkjv_verse_range'),
    path('nkjv_keyword/', views.nkjv_keyword, name='nkjv_keyword'),
    path('nas_bible/', views.nas_bible, name='nas_bible'),
    path('nas_chapters/', views.nas_chapters, name='nas_chapters'), 
    path('nas_verse/', views.nas_verse, name='nas_verse'),
    path('nas_verse_range/', views.nas_verse_range, name='nas_verse_range'),
    path('nas_keyword/', views.nas_keyword, name='nas_keyword'),
    path('niv_bible/', views.niv_bible, name='niv_bible'),
    path('niv_chapters/', views.niv_chapters, name='niv_chapters'), 
    path('niv_verse/', views.niv_verse, name='niv_verse'),
    path('niv_verse_range/', views.niv_verse_range, name='niv_verse_range'),
    path('niv_keyword/', views.niv_keyword, name='niv_keyword'),
]        
