# Generated by Django 4.2.7 on 2023-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_id', models.CharField(choices=[('1', 'AMP Bible'), ('2', 'ESV Bible'), ('3', 'KJV Bible'), ('4', 'NKJV Bible'), ('5', 'NAS Bible'), ('6', 'NIV Bible')], max_length=1)),
                ('bible_name', models.CharField(max_length=50, null=True)),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50, null=True)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AMPBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ESVBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KJVBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NASBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NIVBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NKJVBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(choices=[('1', 'Genesis'), ('2', 'Exodus'), ('3', 'Leviticus'), ('4', 'Numbers'), ('5', 'Deuteronomy'), ('6', 'Joshua'), ('7', 'Judges'), ('8', 'Ruth'), ('9', '1 Samuel'), ('10', '2 Samuel'), ('11', '1 Kings'), ('12', '2 Kings'), ('13', '1 Chronicles'), ('14', '2 Chronicles'), ('15', 'Ezra'), ('16', 'Nehemiah'), ('17', 'Esther'), ('18', 'Job'), ('19', 'Psalm'), ('20', 'Proverbs'), ('21', 'Ecclesiastes'), ('22', 'Song of Solomon'), ('23', 'Isaiah'), ('24', 'Jeremiah'), ('25', 'Lamentations'), ('26', 'Ezekiel'), ('27', 'Daniel'), ('28', 'Hosea'), ('29', 'Joel'), ('30', 'Amos'), ('31', 'Obadiah'), ('32', 'Jonah'), ('33', 'Micah'), ('34', 'Nahum'), ('35', 'Habakkuk'), ('36', 'Zephaniah'), ('37', 'Haggai'), ('38', 'Zechariah'), ('39', 'Malachi'), ('40', 'Matthew'), ('41', 'Mark'), ('42', 'Luke'), ('43', 'John'), ('44', 'Acts'), ('45', 'Romans'), ('46', '1 Corinthians'), ('47', '2 Corinthians'), ('48', 'Galatians'), ('49', 'Ephesians'), ('50', 'Philippians'), ('51', 'Colossians'), ('52', '1 Thessalonians'), ('53', '2 Thessalonians'), ('54', '1 Timothy'), ('55', '2 Timothy'), ('56', 'Titus'), ('57', 'Philemon'), ('58', 'Hebrews'), ('59', 'James'), ('60', '1 Peter'), ('61', '2 Peter'), ('62', '1 John'), ('63', '2 John'), ('64', '3 John'), ('65', 'Jude'), ('66', 'Revelation')], max_length=2)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
