# Generated by Django 4.2.7 on 2023-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AMPBible',
            new_name='AMPCBible',
        ),
        migrations.AlterField(
            model_name='allbibles',
            name='bible_id',
            field=models.CharField(choices=[('1', 'AMPC Bible'), ('2', 'ESV Bible'), ('3', 'KJV Bible'), ('4', 'NKJV Bible'), ('5', 'NAS Bible'), ('6', 'NIV Bible')], max_length=1),
        ),
    ]
